# Generated by Django 3.0.3 on 2020-04-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
    ]
