# Generated by Django 3.0.3 on 2020-04-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200414_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(default='', max_length=16),
        ),
    ]
