# Generated by Django 3.0.3 on 2020-04-18 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200417_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Movie'),
        ),
    ]
